apiVersion: v1
kind: Pod
metadata:
   name: pod-for-log
spec:
   containers:
     - name:  cont-for-log
       image: busybox
       command:  [ "/bin/sh", "-c", "echo Log Level:  $(LOG_LEVEL)  Log Location:  $(LOG_LOCATION)"]
       env:
         - name:  LOG_LEVEL
           valueFrom:
             configMapKeyRef:
              name:  log-config
              key: log.level
         - name:  LOG_LOCATION
           valueFrom:
             configMapKeyRef:
               name:  log-config
               key:  log.location
       imagePullPolicy: IfNotPresent
   restartPolicy: Never
