apiVersion: v1
kind: Pod
metadata:
   name: pod-secret
spec:
   containers:
     - name:  cont-secret
       image: busybox
       command:  [ "/bin/sh", "-c", "--"]
       args:  ["while true; do sleep 30; done;"]
       env:
         - name: BUSYBOX_PASSWORD
           valueFrom:
             secretKeyRef:
              name:  mysql-pass
              key: password
       imagePullPolicy: IfNotPresent
   restartPolicy: Never

