apiVersion: v1
kind: Pod
metadata:
   name: pod-secret-vol
spec:
   containers:
     - name:  cont-secret
       image: busybox
       command:  [ "/bin/sh", "-c", "--"]
       args:  ["while true; do sleep 30; done;"]
       volumeMounts:
       - name: secret-vol
         mountPath: "/etc/secret-data"
         readOnly: true
   volumes:
   - name: secret-vol
     secret: 
       secretName: mysql-pass       

