apiVersion: v1
kind: Pod
metadata:
  name: simple-svc
  labels:
    app: ss
spec:
  containers:
  - name: hello-world
    image: gcr.io/google-samples/hello-app:1.0
    ports:
    - containerPort: 80
