apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: SERVICE_IP
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to DB_IP
              name: my-config1
              # Specify the key associated with the value
              key: SERVICE_IP
