apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot-faile
  labels:
    example: jobs
spec:
  template:
    metadata:
      labels:
        example: jobs
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-exit-code=1"
        - "--keygen-num-to-gen=3"
      restartPolicy: OnFailure
