kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvpvcsc1
spec:
  storageClassName: local-sc
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
