apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo
  namespace: mem-cpu
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "50Mi"
        cpu: "100m" 
      requests:
        memory: "25Mi"
        cpu: "50m"
